# Generated by Django 3.0.7 on 2020-06-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtech', '0002_auto_20200629_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='upload/', verbose_name='')),
            ],
        ),
    ]
